Repository PartyGwam/api, pull requests merged in 2018-06, with the labels that each got.

#6 #4 - 스테이지 서버(heroku) 배포 환경설정
  Procfile
  pg_rest_api/settings/__init__.py
Labels: 백엔드, 환경설정

#21 #9 - 로그인 회원가입 구현
  .gitignore
  api/users/permissions.py
  api/users/serializers.py
  api/users/urls.py
  api/users/views.py
  apps/profiles/migrations/0003_profile_username.py
  apps/profiles/migrations/0004_auto_20180628_2009.py
  apps/profiles/models.py
  apps/users/models.py
  apps/users/views.py
  requirements.txt
Labels: users, 백엔드, 새로운 기능, 우선순위 높음

#23 Develop
  .gitignore
  api/parties/pagination.py
  api/parties/permissions.py
  api/parties/serializers.py
  api/parties/urls.py
  api/parties/views.py
  api/profiles/serializers.py
  api/profiles/urls.py
  api/profiles/views.py
  api/users/permissions.py
  api/users/serializers.py
  api/users/urls.py
  api/users/views.py
  apps/comments/migrations/0001_initial.py
  apps/comments/migrations/0002_comment_slug.py
  apps/comments/views.py
  apps/complains/migrations/0001_initial.py
  apps/complains/views.py
  apps/notifications/migrations/0001_initial.py
  apps/notifications/migrations/0002_notification_slug.py
  apps/notifications/views.py
  apps/parties/migrations/0001_initial.py
  apps/parties/migrations/0002_auto_20180625_2012.py
  apps/parties/models.py
  apps/parties/views.py
  apps/profiles/migrations/0001_initial.py
  apps/profiles/migrations/0002_auto_20180625_2012.py
  apps/profiles/models.py
  apps/profiles/views.py
  apps/users/migrations/0001_initial.py
  apps/users/models.py
  apps/users/views.py
  pg_rest_api/pagination.py
  pg_rest_api/settings/components/rest-framework.py
  requirements.txt
Labels: 배포

#24 Hotfix: 이메일 및 닉네임 실시간 검증을 위한 API 추가
  api/users/serializers.py
  api/users/urls.py
  api/users/views.py
Labels: users, 기능 수정, 백엔드

#25 Develop
  api/users/serializers.py
  api/users/urls.py
  api/users/views.py
Labels: 배포
